# -*- coding: utf-8 -*-
"""Verity_Global_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JPPf4Jos9-mx-muPenL_uN19gbYBEGtI
"""

import streamlit as st
import pandas as pd
import numpy as np
import time
import plotly.express as px
from datetime import datetime

# --- 1. SETUP ---
st.set_page_config(page_title="Verity Global", layout="wide")
st.title("🛡️ Verity Global: Enterprise Fraud Monitor")

# --- 2. DATABASE ---
HUBS = {
    "North America": (40.7, -74.0), "Europe": (51.5, -0.1),
    "Asia": (35.6, 139.6), "South America": (-23.5, -46.6), "Africa": (6.5, 3.3)
}
IND = ["Retail", "Crypto", "Travel", "Electronics", "Luxury", "Banking"]
MERCHANTS = ["Amazon", "Apple Store", "Starbucks", "Binance", "Delta Air", "Shell", "Walmart", "Target"]

ALL_ZONES = []
for reg, coords in HUBS.items():
    for i in range(1, 11):
        ALL_ZONES.append({"name": f"{reg} Z{i}", "reg": reg, "lat": coords[0], "lon": coords[1]})

# --- 3. STATE ---
if 'data' not in st.session_state: st.session_state.data = []
if 'f_val' not in st.session_state: st.session_state.f_val = 0.0

# --- 4. UI SKELETON ---
with st.sidebar:
    st.subheader("📊 Security Health")
    status_box = st.empty()
    st.subheader("🗺️ Regional Risk")
    risk_box = st.empty()
    st.subheader("🏢 Industry Attack Surface")
    ind_box = st.empty()
    if st.button("Reset Session"):
        st.session_state.data, st.session_state.f_val = [], 0.0
        st.rerun()

m1, m2, m3 = st.columns(3)
fraud_k, node_k, lat_k = m1.empty(), m2.empty(), m3.empty()

col1, col2 = st.columns([2, 1])
with col1:
    map_placeholder = st.empty()
    st.subheader("📡 Global Event Log")
    log_box = st.empty()

# --- 5. MAIN LOOP ---
while True:
    start = time.time()

    # DYNAMIC LOGIC: Generate 1-5 Verified transactions for every loop to ensure volume
    num_tx = np.random.randint(1, 6)
    for i in range(num_tx):
        z = np.random.choice(ALL_ZONES)
        # 1 in 15 chance to be blocked, otherwise verified
        is_blocked = np.random.random() < 0.07
        current_status = "Blocked" if is_blocked else "Verified"
        current_amt = round(np.random.exponential(120) + 10, 2)

        tx = {
            "time": datetime.now().strftime("%H:%M:%S"),
            "Merchant": np.random.choice(MERCHANTS),
            "Amount": current_amt,
            "Location": z["name"],
            "lat": z["lat"], "lon": z["lon"],
            "reg": z["reg"], "ind": np.random.choice(IND),
            "Status": current_status
        }

        if current_status == "Blocked":
            st.session_state.f_val += current_amt

        st.session_state.data.append(tx)

    df = pd.DataFrame(st.session_state.data)
    iter_key = len(df)

    # Metrics
    fraud_k.metric("Fraud Blocked", f"${st.session_state.f_val:,.2f}")
    node_k.metric("Active Nodes", len(df["Location"].unique()))
    lat_k.metric("Latency", f"{(time.time()-start)*1000:.1f}ms")

    # --- 6. REFRESH VISUALS ---
    map_placeholder.map(df.tail(30)) # Show slightly more points for activity
    log_box.dataframe(df[["time", "Merchant", "Amount", "Location", "Status"]].tail(10), use_container_width=True)

    # Health Chart: Dynamic Scaling
    h_counts = df.groupby("Status").size().reindex(["Verified", "Blocked"], fill_value=0).reset_index()
    h_counts.columns = ["Status", "Count"]
    fig = px.bar(h_counts, x="Status", y="Count", color="Status",
                 color_discrete_map={"Verified":"#00CC96","Blocked":"#EF553B"},
                 category_orders={"Status": ["Verified", "Blocked"]})
    fig.update_layout(height=220, margin=dict(l=0,r=0,t=0,b=0), showlegend=False)
    status_box.plotly_chart(fig, use_container_width=True, key=f"s_{iter_key}")

    # Risk Charts: Restored Full Analytics
    f_df = df[df["Status"]=="Blocked"]
    if not f_df.empty:
        # Regional Risk (Restored to show all regions)
        r_counts = f_df.groupby("reg").size().reset_index()
        r_counts.columns = ["Region", "Count"]
        fig2 = px.bar(r_counts, x="Region", y="Count", color="Region")
        fig2.update_layout(height=200, margin=dict(l=0,r=0,t=0,b=0), showlegend=False)
        risk_box.plotly_chart(fig2, use_container_width=True, key=f"r_{iter_key}")

        # Industry Risk (Restored to show full attack surface)
        i_counts = f_df.groupby("ind").size().reset_index()
        i_counts.columns = ["Industry", "Attempts"]
        fig3 = px.pie(i_counts, names="Industry", values="Attempts", hole=0.4,
                      color_discrete_sequence=px.colors.qualitative.Pastel)
        fig3.update_layout(height=200, margin=dict(l=0,r=0,t=0,b=0), showlegend=False)
        ind_box.plotly_chart(fig3, use_container_width=True, key=f"i_{iter_key}")

    time.sleep(0.6) # Slightly faster refresh